In [ ]:
import pandas as pd # Pandas → Data manipulation

Load the datasets

In [2]:


patients = pd.read_csv("../data/raw_data/patients.csv")
appointments = pd.read_csv("../data/raw_data/appointments.csv")
billing = pd.read_csv("../data/raw_data/billing.csv")
doctors = pd.read_csv("../data/raw_data/doctors.csv")

In [3]:
patients.head()

,patient_id,full_name,gender,age,phone_number,email,city,registration_date
0,P01600,Mary Nwosu,M,12,0808-783-0713,not_an_email,Kano,24/04/2023
1,P00162,Grace Ogunleye,NaN,25,0802 815 3780,NaN,Benin city,"Aug 28, 2024"
2,P00986,David Garba,NaN,15,NaN,david.garba474@email.com,Lagos,2024/09/06
3,P00503,GRACE NWOSU,female,-5,0809-542-1859,NaN,ABUJA,2022-08-24
4,P00463,Tolu Ojo,NaN,NaN,0800-757-8203,tolu.ojo372@email.com,Benin city,26/04/2026

In [4]:
patients

,patient_id,full_name,gender,age,phone_number,email,city,registration_date
0,P01600,Mary Nwosu,M,12,0808-783-0713,not_an_email,Kano,24/04/2023
1,P00162,Grace Ogunleye,NaN,25,0802 815 3780,NaN,Benin city,"Aug 28, 2024"
2,P00986,David Garba,NaN,15,NaN,david.garba474@email.com,Lagos,2024/09/06
3,P00503,GRACE NWOSU,female,-5,0809-542-1859,NaN,ABUJA,2022-08-24
4,P00463,Tolu Ojo,NaN,NaN,0800-757-8203,tolu.ojo372@email.com,Benin city,26/04/2026
...,...,...,...,...,...,...,...,...
1665,P01559,Grace Balogun,female,46,8053985671,grace.balogun38@yahoo.com,IBADAN,2024-10-08
1666,P01184,Amaka Sani,Female,28,+2348010265670,AMAKA.SANI916@GMAIL.COM,lagos,2022/09/09
1667,P00494,Tunde Usman,female,Thirty-Five,0804 029 4698,tunde.usman30@email.com,Port Harcourt,2021-07-15
1668,P00528,Hannah Johnson,female,Thirty-Five,08077024790,hannah.johnson285@yahoo.com,ibadan,2024-05-15
1669,P01193,John Afolabi,NaN,NaN,+2348071099450,john.afolabi498@email.com,Abuja,2022-07-31

Data Exploration on the Patients Dataset

In [5]:
patients.shape

(1670, 8)

In [6]:
patients.dtypes

patient_id           str
full_name            str
gender               str
age                  str
phone_number         str
email                str
city                 str
registration_date    str
dtype: object

In [7]:
patients.info()

<class 'pandas.DataFrame'>
RangeIndex: 1670 entries, 0 to 1669
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   patient_id         1633 non-null   str
 1   full_name          1670 non-null   str
 2   gender             1241 non-null   str
 3   age                1083 non-null   str
 4   phone_number       1525 non-null   str
 5   email              1211 non-null   str
 6   city               1670 non-null   str
 7   registration_date  1670 non-null   str
dtypes: str(8)
memory usage: 104.5 KB

In [8]:
patients.isnull().sum()

patient_id            37
full_name              0
gender               429
age                  587
phone_number         145
email                459
city                   0
registration_date      0
dtype: int64

Checking for Duplicate

In [9]:
patients.duplicated().sum()

np.int64(70)

Clean dublicate in the Patients Dataset

In [10]:
patients = patients.drop_duplicates()

Standardizing the city column

In [11]:
# Before carrying out standardization, let's check the data types of the patients dataset
patients["city"].unique()

<StringArray>
[         'Kano',    'Benin city',         'Lagos',         'ABUJA',
         'enugu',        'ibadan', 'PORT HARCOURT', 'Port Harcourt',
         'lagos',        'IBADAN',         'abuja',         'Abuja',
 'port harcourt',         'LAGOS',          'kano',        'Ibadan',
         'LaGoS',         'ENUGU']
Length: 18, dtype: str

In [12]:
# Standardizing the city names in the patients dataset 
patients["city"] = patients["city"].str.title()

In [13]:
# After carrying out standardization, let's check the data types of the patients dataset
patients["city"].unique()

<StringArray>
['Kano', 'Benin City', 'Lagos', 'Abuja', 'Enugu', 'Ibadan', 'Port Harcourt']
Length: 7, dtype: str

In [14]:
patients

,patient_id,full_name,gender,age,phone_number,email,city,registration_date
0,P01600,Mary Nwosu,M,12,0808-783-0713,not_an_email,Kano,24/04/2023
1,P00162,Grace Ogunleye,NaN,25,0802 815 3780,NaN,Benin City,"Aug 28, 2024"
2,P00986,David Garba,NaN,15,NaN,david.garba474@email.com,Lagos,2024/09/06
3,P00503,GRACE NWOSU,female,-5,0809-542-1859,NaN,Abuja,2022-08-24
4,P00463,Tolu Ojo,NaN,NaN,0800-757-8203,tolu.ojo372@email.com,Benin City,26/04/2026
...,...,...,...,...,...,...,...,...
1664,P00300,Michael Johnson,Male,Thirty-Five,0808 083 0429,michael.johnson_email.com,Lagos,2024-10-07
1665,P01559,Grace Balogun,female,46,8053985671,grace.balogun38@yahoo.com,Ibadan,2024-10-08
1667,P00494,Tunde Usman,female,Thirty-Five,0804 029 4698,tunde.usman30@email.com,Port Harcourt,2021-07-15
1668,P00528,Hannah Johnson,female,Thirty-Five,08077024790,hannah.johnson285@yahoo.com,Ibadan,2024-05-15
1669,P01193,John Afolabi,NaN,NaN,+2348071099450,john.afolabi498@email.com,Abuja,2022-07-31

Cleaning the Gender coloumn

In [15]:
patients["gender"].unique()

<StringArray>
['M', nan, 'female', 'Female', 'male', 'Male', 'F']
Length: 7, dtype: str

In [16]:
# Standardization being carried out
patients["gender"] = patients["gender"].replace({
    "M":"Male",
    "F":"Female",
    "male":"Male",
    "female":"Female"
})

In [17]:
patients["gender"].unique()

<StringArray>
['Male', nan, 'Female']
Length: 3, dtype: str

In [ ]:
# Filling missing gender nan
patients["gender"] = patients["gender"].fillna("Unknown")